<a href="https://colab.research.google.com/github/jmh0411/Stats_SPR2025/blob/main/W05_1_20202505_%EC%9E%A5%EB%AA%85%ED%98%B8_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
a = np.array([[2,3],[5,2]])
a

array([[2, 3],
       [5, 2]])

In [ ]:
print(a)

[[2 3]
 [5 2]]


In [ ]:
a.shape

(2, 2)

In [ ]:
d= np.array([[1,2,3,4,5],[2,4,5,6,7],[5,7,8,9,9]])
d

array([[1, 2, 3, 4, 5],
       [2, 4, 5, 6, 7],
       [5, 7, 8, 9, 9]])

In [ ]:
d.shape

(3, 5)

In [ ]:
d[1][2]

np.int64(5)

In [ ]:
d[1,2]

np.int64(5)

In [ ]:
d[1: ,3:]

array([[6, 7],
       [9, 9]])

In [ ]:
d= np.array([2,3,4,5,6])
d.shape

(5,)

In [ ]:
e = np.array([[1,2,3,4],[3,4,5,6]])
e.shape

(2, 4)

In [ ]:
data = np.arange(1,5)
data.dtype

dtype('int64')

In [ ]:
data.astype('float64')

array([1., 2., 3., 4.])

In [ ]:
data.astype('int32')

array([1, 2, 3, 4], dtype=int32)

In [ ]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
t = np.zeros((5,3))
t

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
t.transpose().shape

(3, 5)

In [ ]:
arr1 = np.array([[2,3,4],[6,7,8]])
arr2 = np.array([[12,23,14],[36,47,58]])

In [ ]:
arr1+arr2

array([[14, 26, 18],
       [42, 54, 66]])

In [ ]:
arr1*arr2

array([[ 24,  69,  56],
       [216, 329, 464]])

In [ ]:
arr3 = np.array([100,200,300])

In [ ]:
arr1 +arr3

array([[102, 203, 304],
       [106, 207, 308]])

In [ ]:
arr5= np.array([[9],[3]])

In [ ]:
arr5+arr1

array([[11, 12, 13],
       [ 9, 10, 11]])

In [ ]:
arr4 = np.arange(1,11)

In [ ]:
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr4+arr1

ValueError: operands could not be broadcast together with shapes (10,) (2,3) 

In [ ]:
d

array([2, 3, 4, 5, 6])

In [ ]:
d= np.array([[1,2,3,4,5],[2,4,5,6,7],[5,7,8,9,9]])
d_list = [[1,2,3,4,5],[2,4,5,6,7],[5,7,8,9,9]]

In [ ]:
d_list

[[1, 2, 3, 4, 5], [2, 4, 5, 6, 7], [5, 7, 8, 9, 9]]

In [ ]:
d

array([[1, 2, 3, 4, 5],
       [2, 4, 5, 6, 7],
       [5, 7, 8, 9, 9]])

In [ ]:
d_list[:2] = 0

In [ ]:
d[:2] = 0

In [ ]:
d

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [5, 7, 8, 9, 9]])

In [ ]:
np.arange(10)
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr4[:5]

array([1, 2, 3, 4, 5])

In [ ]:
arr4[-3:]

array([ 8,  9, 10])

In [ ]:
arr1

array([[2, 3, 4],
       [6, 7, 8]])

In [ ]:
arr1[1,2]

np.int64(8)

In [ ]:
arr1[ :,2].shape

(2,)

In [ ]:
import os usecsv
import numpy as np
os.chdir(r':/content/usecsv.py')
quest = np.array(usecsv.switch(usecsv.opencsv('quest.csv')))
quest

SyntaxError: invalid syntax (<ipython-input-90-64d5d4ab59ba>, line 1)

In [ ]:
quest = np.array(usecsv.switch(usecsv.opencsv('quest.csv')))
quest

NameError: name 'usecsv' is not defined

In [ ]:
quest >5

NameError: name 'quest' is not defined

In [ ]:
quest [quest >5]= 5
quest

NameError: name 'quest' is not defined

In [ ]:
usecsv.writecsv('result.csv', list(quest))

NameError: name 'usecsv' is not defined